In [3]:
import pandas as pd

In [4]:
import numpy as np

In [3]:
# 1 . Write a program using list comprehension to find primes in range 2 to 100
primes = [i for i in range(2,100) if all(i%j != 0 for j in range(2, int(i ** 0.5) + 1))]
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [4]:
# Q.2 Write a function to reverse a string.
# Python code to reverse a string
# using recursion
s = str(input("enter the string = "))
# give input user chandraprakash
def reverse(s):
    if len(s) == 0:
        return s
    else:
        return reverse(s[1:]) + s[0]

print ("The original string is : ",end="")
print (s)

print ("The reversed string(using recursion) is : ",end="")
print (reverse(s))


enter the string = chandru
The original string is : chandru
The reversed string(using recursion) is : urdnahc


In [5]:
#3. write a program to extract the words from the given list which have their first character in uppercase.

Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']
Days
# Output: ['Monday', 'Sunday', 'Saturday']
    
output = []
for d in Days:
    if d[0].isupper() == True:
        output.append(d)
print(output)


['Monday', 'Sunday', 'Saturday']


In [3]:

import datetime

In [4]:
# 4.Write a program to extract the year part from the dates in the given list.

Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']
print(Batch)
# Output: ['1997','2011','1993','2020']


dat=[]
for i in Batch: 
    dat.append(datetime.datetime.strptime(i,'%d-%m-%Y'))  
year=[]
for i in dat:
    year.append(i.year)
year

['15-06-1997', '15-06-2011', '15-06-1993', '15-06-2020']


[1997, 2011, 1993, 2020]

In [107]:
# 5.write a program swap the keys to values and values to keys of the given dictionary


Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}
new_module = dict([(value, key) for key, value in Module.items()])
print ("module : ")
print(Module) 
print()
print ("Dictionary after swapping is :  ") 
print("keys: values")
for i in new_module:
    print(i, " :  ", new_module[i])

module : 
{'Data Science': 1, 'Machine Learning': 2, 'SQL': 3, 'Big Data': 4}

Dictionary after swapping is :  
keys: values
1  :   Data Science
2  :   Machine Learning
3  :   SQL
4  :   Big Data


In [1]:
# Q.6 write a program to calculate the cumulative average of the given list using accumulate() and lambda function.


def nums_cumulative_sum(nums_list):
    return [sum(nums_list[:i+1]) for i in range(len(nums_list))]

print(nums_cumulative_sum([5,2,1,4,6]))


# or
import itertools
import operator
Input_List = [5,2,1,4,6]
Output_List = itertools.accumulate(Input_List,operator.add)
cnt = 0
for i in Output_List:
    cnt += 1
    pass
print(i/cnt)



3.6


In [10]:
#  7.Write a program to count the number of elements in the string (given by the user)
#that are not present in the 'my_string'. 
#Do not count the white spaces

sentence = input("Enter the sentence: ")
string = sentence.lower() or sentence.upper()
print(string)
count = 0
my_string = 'Data Science'
for char in string:
    if char not in my_string:
        count = count + 1
print("number of string in the given sentence :",count)

Enter the sentence: c    h   d 
c    h   d 
number of string in the given sentence : 2


In [ ]:
#8. Define a function to check whether a number is in a range (1000,10000) or not

def test_range(n):
    if n in range(1000,10000):
        print( " %s is in the range"%str(n))
    else :
        print(" %s The number is outside the given range."%str(n))
print(test_range(9586))
print(test_range(986))


In [165]:
#9. Write a program to print pascal triangle upto 6 steps (using list)
n = int(input("enter the number of rows"))
list1 = []
for i in range(n):
    temp_list=[]
    for j in range(i+1):
        if j==0 or j==i:
            temp_list.append(1)
        else:
            temp_list.append(list1[i-1][j-1] + list1[i-1][j])
    list1.append(temp_list)

    
for i in range(n):
    for j in range(n-i-1):
        print(format(" ","<2"),end="")
    for j in range(i+1):
        print(format(list1[i][j],"<3"),end=" ")
    print()
    

enter the number of rows6
          1   
        1   1   
      1   2   1   
    1   3   3   1   
  1   4   6   4   1   
1   5   10  10  5   1   


In [171]:
#10.  Write a program to calculate the sum of all elements in the list.
test_score = [10, 32, 23, 14, 25]

total = 0

for ele in range(0, len(test_score)):
    total = total + test_score[ele]
print("su of all elemnets",total)

su of all elemnets 104


In [176]:
# 11.Find the minimum value along each of the rows.

Score = np.array([[210, 402, 383],
[140, 375, 106],
[140, 125, 217],
[292, 240, 295]])
Score

Score.min(axis=1)

array([210, 106, 125, 240])

In [144]:
#12. Replace all even numbers in the array with -1.

num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])
num_array

print(np.array([x if ((x % 2 != 0) or (x==0)) else -1 for x in num_array]))

#or

[ 0 21 -1 13 -1 45 -1 -1 -1 -1 65 -1 -1]


In [4]:
import numpy as np

In [11]:
x = np.arange(2000)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[   0    1    2 ... 1997 1998 1999]
[1999]


In [13]:
lst = []
 
num = int(input('How many numbers: '))
 
for n in range(num):
    numbers = int(input('Enter number '))
    lst.append(numbers)
     
print("Maximum element in the list is :", max(lst))

How many numbers: 5
Enter number 6
Enter number 7
Enter number 8
Enter number 9
Enter number 2
Maximum element in the list is : 9


In [4]:
lst = []
num = int(input("how many numbers want to compare : "))

for x in range(num):
    numbers = int(input("enter the numbers : "))
    lst.append(numbers)

print("maximum number : ", max(lst))

how many numbers want to compare : 5
enter the numbers : 56
enter the numbers : 56
enter the numbers : 36
enter the numbers : 153
enter the numbers : 1021
maximum number :  1021
